# Target
# example: Vega J2000
# RA : '18:36:56.6'
# DEC : '+38:47:08.6'
ALT: '40:0:0'
AZ: '90:0:0'

# Date
year : 2024
month : 1
day : 8
hour : 22
minute : 00
seconds : 00

# satellite - only starlink for now
# satArea : 3.14159  # https://www.aanda.org/articles/aa/full_html/2020/04/aa37501-20/aa37501-20.html
# albedo : 0.25
# cross_section = area*albedo
cross_section: 0.075

# Observer
# Durham
lat : 54.7753
lon : 1.5849
alt : 100. # 100.

# FoV
radius : 10.  # degrees
duration : 3600 #3600  # seconds

# Plots
Mmin : 0
Mmax : 10
plotDir : './plots_field/'

fdir: "./plots"
TLEdir: "./TLE"

# logging
verbose: 1
logfile: 'log.txt'
log_level: 'DEBUG'